### PR TITLE
Support for RDF-star term maps. Necessary for Ontop's RDF-star support.

### PR DESCRIPTION
**Pull request by luksun**
@ghxiao This code was produced as part of my thesis work at the university, with professor Calvanese as supervisor and Benjamin Cogrel as support from ontopic's side. Care has been taken to not change the functionality at all except as it relates to the thesis and Ontop's upcoming RDF-star support.

### CODE REVIEW

**Comment by ghxiao** [comment]
Hi @luksun, thanks for the PR. There are some conflicts need to be resolved first. Could you merge the latest develop branch so as to resolve the conflict?

**Comment by luksun** [comment]
Okay, I've resolved the merge conflicts.

**Comment by bcogrel** [comment]
What about using https://w3id.org/obda/r2rmlstar# as prefix for the R2RML extension?

**Comment by luksun** [comment]
The namespace has now been changed.

**Comment by ghxiao** [comment]
Hi @luksun, I have merged the PR. Do you need to make other changes? Otherwise, we should make a new stable release on Maven Central.

**Comment by luksun** [comment]
@ghxiao No need for further changes. I agree it would be nice to have it on maven, I'm unfamiliar with how to publish on maven though.

**Comment by ghxiao** [comment]
I will take care of the Maven release.

**Comment by ghxiao** [comment]
@luksun @bcogrel  The v0.8 release has been made and adopted in Ontop.

**Pull request merged**
